### ISSUE TITLE
v1.8.7 can't turn off wifi anymore

### ISSUE THREAD

**Issue by bungabunga** [j4velin/WiFi-Automatic#48] opened 2019-10-25 17:47 UTC
v1.8.5 worked fine on android 10, (Pixel 3, GrapheneOS)

**Comment by j4velin** [comment] 2019-10-27 13:28
Root cause is that apps are not allowed to toggle WiFi on Android 10 any more, see https://developer.android.com/reference/android/net/wifi/WifiManager.html#setWifiEnabled(boolean)

Fixed by setting the target SDK to Android P again https://github.com/j4velin/WiFi-Automatic/commit/887111eb5a3c0f1d546b3f9ba871e98589cc749a

**Closed by j4velin** 2019-10-27 13:28 UTC
